# Site settings
title: SWJTU problemSolve
email: desgard_duan@foxmail.com
description: "ACM"
permalink: /:year/:month/:day/:title.html
baseurl: ""
url: "https://swjtu-acm.github.io"
atom-baseurl: "https://swjtu-acm.github.io"
author: "hackerxu"

# Build settings
# permalink: date

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,no_intra_emphasis,strikethrough,no_intra_emphasis,autolink,tables]

#duoshuo
  comments :
    provider : duoshuo
    duoshuo :
      short_name : desgard

navigations:
  - title: About
    class: fa fa-list-ul
    href: /about/
  - title: Archive
    class: fa fa-tags
    href: /archive/
  - title: Categories
    class: fa fa-user
    href: /categories/
  - title: Tags
    class: fa fa-film
    href: /tags/
  - title: Rss
    class: fa fa-rss
    href: /atom.xml
